name: xpense_tracker_app
description: A Flutter expense tracker app with printing functionality.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  pdf: ^3.11.3
  printing: ^5.12.0
  image_picker: ^1.0.4
  google_ml_kit: ^0.16.3
  syncfusion_flutter_pdf: ^24.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
